framework:
  website: emmett.sh
  version: 2.1

deps:
  - libffi-dev

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  WORKER_CLASS: emmett.asgi.workers.EmmettWorker
